[project]
name = "tuffysearch-scraper"
version = "1.0.0"
description = "Web scraper to scrape course information from CSUF's course catalog"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["beautifulsoup4>=4.13.4", "requests>=2.32.3", "rich>=14.0.0"]
